import { DateUtil } from 'src/common/utils';
import { Movie } from 'src/modules/movies/schemas/movie.schema';

const DAY_MS = 24 * 60 * 60 * 1000;
const START_DAY = DateUtil.startOfDay('2025-12-01');
const END_DAY = DateUtil.startOfDay('2026-01-31');

function randomInt(min: number, max: number) {
  return Math.floor(Math.random() * (max - min + 1)) + min;
}

const generateRandomDates = (): { releaseDate: Date; endDate: Date } => {
  const totalDays = Math.max(
    1,
    Math.floor((END_DAY.getTime() - START_DAY.getTime()) / DAY_MS),
  );

  const offsetDays = randomInt(0, totalDays);
  const releaseDate = DateUtil.addDays(START_DAY, offsetDays);

  const durationDays = randomInt(14, 28);
  const endDate = DateUtil.endOfDay(
    DateUtil.addDays(releaseDate, durationDays),
  );

  return {
    releaseDate,
    endDate,
  };
};

// --- MAIN DATA ---
export const MOVIES_DATA: Partial<Movie>[] = [
  {
    title: 'HOÀNG TỬ QUỶ (T18)',
    genres: ['Horror'],
    duration: 117,
    description:
      'Hoàng Tử Quỷ xoay quanh Thân Đức - một hoàng tử được sinh ra nhờ tà thuật. Trốn thoát khỏi cung cấm, Thân Đức tham vọng giải thoát Quỷ Xương Cuồng khỏi Ải Mắt Người để khôi phục Xương Cuồng Giáo. Nhưng kế hoạch của Thân Đức chỉ thành hiện thực khi hắn có đủ cả hai “nguyên liệu” - Du Hồn Giả và Bạch Hổ Nguyên Âm. Đội lốt một lang y hiền lành, muốn chữa bệnh cứu người, Thân Đức lên đường đến làng Hủi và đụng độ trưởng làng Lỗ Đạt mạnh mẽ, liệu hắn có thể đạt được âm mưu tà ác của mình?',
    posterUrl:
      'https://cinestar.com.vn/_next/image/?url=https%3A%2F%2Fapi-website.cinestar.com.vn%2Fmedia%2Fwysiwyg%2FPosters%2F12-2025%2Fhoang-tu-quy-main.png&w=1920&q=75',
    trailerUrl: 'https://youtu.be/oLxbSoA389c',
    ratingAge: 'C13',
    country: 'Vietnam',
    language: 'Vietnamese',
    actors: [
      'Anh Tú Atus',
      'Lương Thế Thành',
      'Hoàng Linh Chi',
      'Huỳnh Thanh Trực',
      'Rima Thanh Vy',
      'Lê Hà Phương',
      'Duy Luân',
    ],
    director: 'Trần Hữu Tấn',
    producer: 'Hoàng Quân',
    ...generateRandomDates(),
  },
  {
    title: 'TRUY TÌM LONG DIÊN HƯƠNG (T16)',
    genres: ['Comedy', 'Action'],
    duration: 103,
    description:
      'Ngay trước thềm lễ hội lớn, bảo vật linh thiêng Long Diên Hương bất ngờ bị đánh cắp, kéo theo hai anh em Tâm - Tuấn cùng nhóm bạn vào chuyến hành trình nghẹt thở nhưng không kém phần hài hước khi họ phải chạm trán với các băng nhóm ngư dân xã hội đen cùng nhiều hiểm nguy.',
    posterUrl:
      'https://cinestar.com.vn/_next/image/?url=https%3A%2F%2Fapi-website.cinestar.com.vn%2Fmedia%2Fwysiwyg%2FPosters%2F11-2025%2Ftruy-tien-long-dien-huong-poster.jpg&w=1920&q=75',
    trailerUrl: 'https://youtu.be/fO6X58qWA_s',
    ratingAge: undefined,
    country: 'Vietnam',
    language: 'Vietnamese',
    actors: ['Quang Tuấn', 'Ma Ran Đô', 'Hoàng Tóc Dài', 'Nguyên Thảo'],
    director: 'Dương Minh Chiến',
    producer: undefined,
    ...generateRandomDates(),
  },
  {
    title: '96 PHÚT SINH TỬ (T16) LT',
    genres: ['Action'],
    duration: 119,
    description:
      'Ba năm sau thảm kịch tại trung tâm mua sắm, trên chuyến tàu cao tốc định mệnh, nữ cảnh sát Huỳnh Hân và chồng cô — cựu chuyên gia gỡ bom Tống Khang Nhân — cùng đội trưởng Lý Kiệt bất ngờ nhận được tin nhắn thông báo một quả bom đã được cài sẵn trên tàu. Vụ việc lần này còn phức tạp hơn khi kẻ khủng bố dường tính toán vô cùng tinh vi. Khi thời gian cạn dần, Tống Khang Nhân buộc phải ngăn thảm kịch xảy ra bằng mọi giá, đồng thời đối mặt với những ám ảnh kinh hoàng từ vụ nổ năm xưa.',
    posterUrl:
      'https://cinestar.com.vn/_next/image/?url=https%3A%2F%2Fapi-website.cinestar.com.vn%2Fmedia%2Fwysiwyg%2FPosters%2F12-2025%2F96M.jpg&w=1920&q=75',
    trailerUrl: 'https://youtu.be/H9U8H01_olw',
    ratingAge: undefined,
    country: 'Vietnam',
    language: 'Vietnamese',
    actors: [
      'Lâm Bách Hoành',
      'Tống Vân Hoa',
      'Vương Bá Kiệt',
      'Lý Lý Nhân',
      'Diêu Dĩ Đề',
      'Thái Phàm Hi',
    ],
    director: 'Hồng Tử Huyên',
    producer: undefined,
    ...generateRandomDates(),
  },
  {
    title: 'PHIÊN CHỢ CỦA QUỶ (T18)',
    genres: ['Horror'],
    duration: 97,
    description:
      'Phiên chợ của quỷ - Nơi linh hồn trở thành những món hàng để thỏa mãn tham vọng của con người. Mỗi đêm, cổng chợ âm sẽ mở, quỷ sẽ bắt hồn. Một khi đã dám bán rẻ linh hồn, cái giá phải trả có thể là máu, là thịt, hoặc chính sự tồn tại của những kẻ dám liều mạng.',
    posterUrl:
      'https://cinestar.com.vn/_next/image/?url=https%3A%2F%2Fapi-website.cinestar.com.vn%2Fmedia%2Fwysiwyg%2FPosters%2F12-2025%2Fphien-cho-cua-quy.jpg&w=1920&q=75',
    trailerUrl: 'https://youtu.be/dLmJv83Djyc',
    ratingAge: 'C13',
    country: 'Vietnam',
    language: 'Vietnamese',
    actors: ['Ngọc Xuân', 'Hứa Vĩ Văn', 'Yoo Jae Myung'],
    director: 'Hong Won Ki',
    producer: undefined,
    ...generateRandomDates(),
  },
  {
    title: 'QUÁN KỲ NAM (T16)',
    genres: ['Drama'],
    duration: 135,
    description:
      'Với sự nâng đỡ của người chú quyền lực, Khang được giao công việc dịch cuốn “Hoàng Tử Bé” và dọn vào căn hộ bỏ trống ở khu chung cư cũ. Anh làm quen với cô hàng xóm Kỳ Nam — một góa phụ từng nổi danh trong giới nữ công gia chánh và giờ lặng lẽ với nghề nấu cơm tháng. Một tai nạn xảy ra khiến Kỳ Nam không thể tiếp tục công việc. Khang đề nghị giúp đỡ, và mối quan hệ của họ dần trở nên sâu sắc giữa những biến động xã hội. Liệu tình yêu có giúp họ vượt qua?"',
    posterUrl:
      'https://cinestar.com.vn/_next/image/?url=https%3A%2F%2Fapi-website.cinestar.com.vn%2Fmedia%2Fwysiwyg%2FPosters%2F11-2025%2Fquan-ky-nam-poster.jpg&w=1920&q=75',
    trailerUrl: 'https://youtu.be/27dgpqiI0VU',
    ratingAge: undefined,
    country: 'Vietnam',
    language: 'Vietnamese',
    actors: ['Liên Bỉnh Phát', 'Đỗ Thị Hải Yến', 'Trần Thế Mạnh'],
    director: 'Lê Nhật Quang',
    producer: undefined,
    ...generateRandomDates(),
  },
  {
    title: 'PHÒNG TRỌ MA BẦU',
    genres: ['Comedy', 'Horror'],
    duration: 99,
    description:
      'Hai người bạn thân thuê phải một căn phòng trọ cũ, nơi liên tục xảy ra những hiện tượng kỳ bí. Họ đối mặt với hồn ma của một người phụ nữ mang thai - “ma bầu”. Ẩn sau nỗi ám ảnh rùng rợn là bi kịch và tình yêu mẫu tử thiêng liêng.',
    posterUrl:
      'https://cinestar.com.vn/_next/image/?url=https%3A%2F%2Fapi-website.cinestar.com.vn%2Fmedia%2Fwysiwyg%2FPosters%2F11-2025%2Fphong-tro-ma-bay-payoff.jpg&w=1080&q=75',
    trailerUrl: 'https://youtu.be/aCI_-1TNlkk',
    ratingAge: 'C13',
    country: 'Vietnam',
    language: 'Vietnamese',
    actors: [
      'Huỳnh Phương',
      'Anh Tú',
      'Phương Lan',
      'Cát Phượng',
      'Lý Hùng',
      'Kim Tuyến',
      'Quỳnh Lam',
    ],
    director: 'Ngụy Minh Khang',
    producer: undefined,
    ...generateRandomDates(),
  },
  {
    title: 'PHI VỤ ĐỘNG TRỜI 2 (P)',
    genres: ['Animation'],
    duration: 117,
    description:
      'PHI VỤ ĐỘNG TRỜI 2 — cuộc phiêu lưu hành động hài hước với các nhân vật quen thuộc. (Theo thông tin từ CineStar)',
    posterUrl:
      'https://cinestar.com.vn/_next/image/?url=https%3A%2F%2Fapi-website.cinestar.com.vn%2Fmedia%2Fwysiwyg%2FPosters%2F11-2025%2Fzootopia-2_1.jpg&w=1080&q=75',
    trailerUrl: 'https://youtu.be/5O3LEps6WJY',
    ratingAge: 'P',
    country: 'USA',
    language: 'English',
    actors: ['Jason Bateman', 'Quinta Brunson', 'Fortune Feimster'],
    director: 'Jared Bush, Byron Howard',
    producer: undefined,
    ...generateRandomDates(),
  },
  {
    title: 'KỲ AN NGHỈ (T18)',
    genres: ['Horror'],
    duration: 99,
    description:
      'Liz và Malcolm quyết định kỷ niệm ngày đặc biệt tại cabin hẻo lánh nhưng mọi thứ trở nên kinh hoàng khi Liz phải đối mặt với các hiện tượng siêu nhiên. Khi đêm buông xuống, sự cô đơn, bí ẩn và nỗi sợ trỗi dậy — biến kỳ nghỉ lãng mạn thành cơn ác mộng không lối thoát.',
    posterUrl:
      'https://cinestar.com.vn/_next/image/?url=https%3A%2F%2Fapi-website.cinestar.com.vn%2Fmedia%2Fwysiwyg%2FPosters%2F11-2025%2Fky-an-nghi.jpg&w=1080&q=75',
    trailerUrl: 'https://youtu.be/JJZU5ZXKEnk',
    ratingAge: 'C13',
    country: 'USA',
    language: 'English',
    actors: ['Tatiana Maslany', 'Rossif Sutherland', 'Claire Friesen'],
    director: 'Osgood Perkins',
    producer: undefined,
    ...generateRandomDates(),
  },
  {
    title: 'CƯỚI VỢ CHO CHA (T13)',
    genres: ['Comedy', 'Family'],
    duration: 112,
    description:
      "Ở một xóm nhỏ miền Tây, ông Sáu Sếu sống lủi thủi trong quán cà phê - karaoke, mong con trai Út Tửng từ Sài Gòn về thăm. Khi phát hiện mình mắc trọng bệnh, ông quyết 'cưới vợ cho con' để trọn lời hứa với người vợ quá cố. Nhưng kế hoạch ấy đổ vỡ khi ông phát hiện Tửng có một bí mật động trời và che giấu mọi chuyện. Giữa những xung đột, hiểu lầm và nỗ lực hàn gắn, cha con họ dần học cách thấu hiểu, để rồi mỗi người đều tìm thấy hạnh phúc và bình yên trong chính cuộc hôn nhân của mình.",
    posterUrl:
      'https://cinestar.com.vn/_next/image/?url=https%3A%2F%2Fapi-website.cinestar.com.vn%2Fmedia%2Fwysiwyg%2FPosters%2F11-2025%2Fcuoi-vo-cho-cha-poster.png&w=1920&q=75',
    trailerUrl: 'https://youtu.be/1ffxVmHB4Hk',
    ratingAge: undefined,
    country: 'Vietnam',
    language: 'Vietnamese',
    actors: [],
    director: 'Nguyễn Ngọc Lâm',
    producer: undefined,
    ...generateRandomDates(),
  },
  {
    title: 'TAFITI - NÁO LOẠN SA MẠC (P)',
    genres: ['Animation'],
    duration: 80,
    description:
      'Chú chồn đất Tafiti vốn chỉ mong một cuộc sống yên bình giữa thảo nguyên nhưng số phận đảo lộn khi bạn heo rừng hậu đậu Bristles xuất hiện. Khi ông nội bị rắn độc cắn, Tafiti buộc phải vượt sa mạc khắc nghiệt để tìm bông hoa xanh hiếm có cứu ông. Một hành trình phiêu lưu đầy thử thách và tiếng cười, giúp Tafiti hiểu rằng điều quý giá nhất không phải điểm đến, mà là bạn đồng hành bên cạnh. ',
    posterUrl:
      'https://cinestar.com.vn/_next/image/?url=https%3A%2F%2Fapi-website.cinestar.com.vn%2Fmedia%2Fwysiwyg%2FPosters%2F11-2025%2Ftafiti.jpg&w=1080&q=75',
    trailerUrl: 'https://youtu.be/n9Jv1bEjSgk',
    ratingAge: 'P',
    country: 'Germany',
    language: 'Vietnamese',
    actors: [],
    director: 'Nian Wels',
    producer: undefined,
    ...generateRandomDates(),
  },
  {
    title: 'NĂM ĐÊM KINH HOÀNG 2 (T16)',
    genres: ['Horror', 'Mystery', 'Thriller'],
    duration: 104,
    description:
      "Một năm sau cơn ác mộng siêu nhiên tại Freddy Fazbear's Pizza, thị trấn tổ chức lễ hội Fazfest lấy cảm hứng từ truyền thuyết địa phương. Khi cô bé Abby lén đến gặp lại Freddy và các animatronic, một chuỗi sự kiện kinh hoàng bắt đầu, hé lộ bí mật đen tối bị chôn vùi suốt nhiều thập kỷ.",
    posterUrl:
      'https://cinestar.com.vn/_next/image/?url=https%3A%2F%2Fapi-website.cinestar.com.vn%2Fmedia%2Fwysiwyg%2FPosters%2F12-2025%2Fnam-dem-kinh-hoang.png&w=1080&q=75',
    trailerUrl: undefined,
    ratingAge: undefined,
    country: 'United States',
    language: 'English',
    actors: [
      'Josh Hutcherson',
      'Piper Rubio',
      'Elizabeth Lail',
      'Freddy Carter',
      'Theodus Crane',
      'Wayne Knight',
      'Mckenna Grace',
      'Skeet Ulrich',
      'Matthew Lillard',
    ],
    director: 'Emma Tammi',
    producer: undefined,
    ...generateRandomDates(),
  },
  {
    title: 'GANGSTER VỀ LÀNG (T16) LT',
    genres: ['Comedy'],
    duration: 102,
    description:
      'Câu chuyện về một kẻ sát nhân ẩn náu trong một ngôi làng yên bình ở vùng quê, khi chỉ còn 30 ngày nữa là hết thời hiệu truy tố.',
    posterUrl:
      'https://cinestar.com.vn/_next/image/?url=https%3A%2F%2Fapi-website.cinestar.com.vn%2Fmedia%2Fwysiwyg%2FPosters%2F11-2025%2Fgangster-ve-lang.jpg&w=1080&q=75',
    trailerUrl: 'https://youtu.be/6P5Nt6RdeZY',
    ratingAge: undefined,
    country: 'South Korea',
    language: 'Korean',
    actors: ['Jung Hye-Seong', 'Ji Seung Hyun'],
    director: 'Kim Hee-Seong',
    producer: undefined,
    ...generateRandomDates(),
  },
  {
    title: '5 CENTIMET TRÊN GIÂY (T13)',
    genres: ['Romance', 'Anime'],
    duration: 76,
    description:
      'Câu chuyện cảm động về Takaki và Akari — đôi bạn thuở thiếu thời dần bị chia cắt bởi thời gian và khoảng cách. Qua ba giai đoạn khác nhau trong cuộc đời, bộ phim khắc họa những ký ức, cuộc hội ngộ và sự xa cách, với hình ảnh hoa anh đào rơi — 5 cm/giây — như ẩn dụ cho tình yêu mong manh và thoáng chốc của tuổi trẻ.',
    posterUrl:
      'https://cinestar.com.vn/_next/image/?url=https%3A%2F%2Fapi-website.cinestar.com.vn%2Fmedia%2Fwysiwyg%2FPosters%2F12-2025%2F5cm.jpg&w=1080&q=75',
    trailerUrl: 'https://youtu.be/WI0_CiynFW8',
    ratingAge: undefined,
    country: 'Japan',
    language: 'Japanese',
    actors: [],
    director: 'Makoto Shinkai',
    producer: undefined,
    ...generateRandomDates(),
  },
  {
    title: 'PHIM ĐIỆN ẢNH THÁM TỬ LỪNG DANH CONAN: DƯ ẢNH CỦA ĐỘC NHÃN (K) PĐ',
    genres: ['Animation'],
    duration: 110,
    description:
      'Trên những ngọn núi tuyết của Nagano, một vụ án bí ẩn đã đưa Conan và các thám tử quay lại quá khứ. Khi điều tra một vụ tấn công tại đài quan sát Nobeyama, họ buộc phải đối mặt với quá khứ đau thương bị chôn vùi — và bí ẩn dần hé lộ từng lớp một.',
    posterUrl:
      'https://cinestar.com.vn/_next/image/?url=https%3A%2F%2Fapi-website.cinestar.com.vn%2Fmedia%2Fwysiwyg%2FPosters%2F11-2025%2Fconan-rerun.jpg&w=1080&q=75',
    trailerUrl: undefined,
    ratingAge: 'P',
    country: 'Japan',
    language: 'Japanese',
    actors: [
      'Minami Takayama',
      'Wakana Yamazaki',
      'Rikiya Koyama',
      'Megumi Hayashibara',
    ],
    director: 'Katsuya Shigehara',
    producer: undefined,
    ...generateRandomDates(),
  },
  {
    title: '100 MÉT (P)',
    genres: ['Animation'],
    duration: 106,
    description:
      'Bộ phim kể về hành trình dài hơn 15 năm của hai vận động viên chạy nước rút — một thiên tài bẩm sinh và một người quyết tâm bằng nỗ lực. Qua những cuộc đua, chấn thương và áp lực tâm lý, họ tìm hiểu ý nghĩa thật sự của việc chạy, vượt qua giới hạn bản thân để chạm tới ước mơ.',
    posterUrl:
      'https://cinestar.com.vn/_next/image/?url=https%3A%2F%2Fapi-website.cinestar.com.vn%2Fmedia%2Fwysiwyg%2FPosters%2F11-2025%2F100m-poster.jpg&w=1080&q=75',
    trailerUrl: 'https://youtu.be/g38X4oSElkg',
    ratingAge: undefined,
    country: 'Japan',
    language: 'Japanese',
    actors: [],
    director: 'Kenji Iwaisawa',
    producer: undefined,
    ...generateRandomDates(),
  },
  {
    title: 'PHI VỤ THẾ KỶ: THOẮT ẨN THOẮT HIỆN (T13)',
    genres: ['Thriller', 'Heist', 'Crime'],
    duration: 113,
    description:
      'Tứ Kỵ Sĩ chính thức tái xuất, bắt tay cùng các tân binh ảo thuật gia Gen Z trong một phi vụ đánh cắp kim cương liều lĩnh nhất trong sự nghiệp. Họ phải đối đầu với bà trùm Veronika — một người phụ nữ quyền lực và đầy thủ đoạn, đứng đầu đế chế rửa tiền Vandenberg. Khi kinh nghiệm lão làng của bộ tứ va chạm với công nghệ 4.0 và mạng lưới tội phạm xuyên lục địa, ai sẽ làm chủ cuộc chơi?',
    posterUrl:
      'https://cinestar.com.vn/_next/image/?url=https%3A%2F%2Fapi-website.cinestar.com.vn%2Fmedia%2Fwysiwyg%2FPosters%2F11-2025%2Fphi-vu-the-ki.png&w=1080&q=75',
    trailerUrl: 'https://youtu.be/rt8tzGFN-Fk',
    ratingAge: undefined,
    country: 'United States',
    language: 'English',
    actors: [
      'Jesse Eisenberg',
      'Woody Harrelson',
      'Dave Franco',
      'Isla Fisher',
      'Justice Smith',
      'Dominic Sessa',
      'Rosamund Pike',
      'Ariana Greenblatt',
    ],
    director: 'Ruben Fleischer',
    producer: undefined,
    ...generateRandomDates(),
  },
  {
    title: 'ANH TRAI SAY XE (T16) LT',
    genres: ['Comedy', 'Family'],
    duration: 110,
    description:
      'Nhóm bạn nối khố sau mười năm quyết định thực hiện chuyến du lịch cùng nhau — một hành trình đầy ắp kịch tính lẫn tiếng cười, khi mỗi người mang theo một quá khứ, một nỗi niềm riêng. “Anh trai say xe” kể về tình bạn, tuổi trẻ và phút giây đậm chất thanh xuân mà không thể nào quên.',
    posterUrl:
      'https://cinestar.com.vn/_next/image/?url=https%3A%2F%2Fapi-website.cinestar.com.vn%2Fmedia%2Fwysiwyg%2FPosters%2F11-2025%2Fanh-trai-say-xe.jpg&w=1080&q=75',
    trailerUrl: 'https://youtu.be/15FPFsXcR-c',
    ratingAge: undefined,
    country: 'South Korea',
    language: 'Korean',
    actors: [
      'Kang Ha Neul',
      'Cha Eun Woo',
      'Kim Young Kwang',
      'Kang Young Suk',
      'Han Seon Hwa',
    ],
    director: 'Nam Dae Jung',
    producer: undefined,
    ...generateRandomDates(),
  },
  {
    title: 'MA LỦNG TƯỜNG (T18)',
    genres: ['Horror'],
    duration: 99,
    description:
      'Một gia đình chết một cách khủng khiếp. Một cô gái bị buộc tội là kẻ giết người. Nhưng một sự thật kinh hoàng hơn đang chờ được tiết lộ. Cuộc chiến trừ tà đẫm máu và gây choáng nhất cuối năm giữa hậu duệ một gia tộc diệt quỷ cùng những thế lực tà ác khủng khiếp nhất xứ vạn đảo.',
    posterUrl:
      'https://cinestar.com.vn/_next/image/?url=https%3A%2F%2Fapi-website.cinestar.com.vn%2Fmedia%2Fwysiwyg%2FPosters%2F12-2025%2Fma-lung-tuong-poster.jpg&w=1080&q=75',
    trailerUrl: 'https://youtu.be/7I-PtAD_TGM',
    ratingAge: 'C13',
    country: 'Indonesia',
    language: 'Indonesian',
    actors: ['Satine Zaneta', 'Niken Anjani'],
    director: 'Tomy Dewo',
    producer: undefined,
    ...generateRandomDates(),
  },
  {
    title: 'SCARLET',
    genres: ['Animation', 'Fantasy'],
    duration: 99,
    description:
      'Từ đạo diễn Mamoru Hosoda — người từng được đề cử Oscar — “Scarlet” là cuộc phiêu lưu vượt thời gian, kể về một nàng công chúa thời trung cổ mang tên Scarlet lên đường trả thù cho cái chết của cha mình. Sau khi bị thương nặng và lạc vào vùng đất tử thần, cô được một chàng trai thời hiện đại cứu giúp và mở ra cơ hội tìm đến tương lai không còn thù hận. Khi đối mặt với kẻ sát nhân, Scarlet phải đấu tranh để phá vỡ vòng lặp hận thù và tìm lại ý nghĩa thật sự của cuộc sống. ',
    posterUrl:
      'https://cinestar.com.vn/_next/image/?url=https%3A%2F%2Fapi-website.cinestar.com.vn%2Fmedia%2Fwysiwyg%2FPosters%2F12-2025%2Fscarlet.jpg&w=1080&q=75',
    trailerUrl: 'https://youtu.be/zh5y1QWIL-g',
    ratingAge: undefined,
    country: 'Japan',
    language: 'Japanese',
    actors: ['Ashida Mana', 'Okada Masaki', 'Yakusho Koji'],
    director: 'Mamoru Hosoda',
    producer: undefined,
    ...generateRandomDates(),
  },
  {
    title: 'THẾ HỆ KỲ TÍCH (K)',
    genres: ['Family', 'Drama'],
    duration: 124,
    description:
      'Mồ côi cha mẹ từ nhỏ, Tiến - cậu thiếu niên sống cùng bà nội nơi phố cổ Hà Nội - học cách trưởng thành giữa nghèo khó; nhờ tình thương của bà, cháu tìm thấy nghị lực và khát vọng bước vào đời.',
    posterUrl:
      'https://cinestar.com.vn/_next/image/?url=https%3A%2F%2Fapi-website.cinestar.com.vn%2Fmedia%2Fwysiwyg%2FPosters%2F12-2025%2Fthe-he-ky-tich.jpg&w=1080&q=75',
    trailerUrl: 'https://youtu.be/YH734HLCDpo',
    ratingAge: undefined,
    country: 'Vietnam',
    language: 'Vietnamese',
    actors: [
      'Trần Tú',
      'NSND Thanh Hoa',
      'NSND Trần Lực',
      'NSND Bùi Bài Bình',
      'NSƯT Chiều Xuân',
      'Quách Thu Phương',
      'Hà Hương',
      'Tuấn Hưng',
      'Nàng Mơ',
    ],
    director: 'Hoàng Nam',
    producer: undefined,
    ...generateRandomDates(),
  },
  {
    title: 'MẮC BẪY LŨ TÍ QUẬY (P) LT',
    genres: ['Animation'],
    duration: 80,
    description:
      'Một gia đình kéo nhau về căn nhà bỏ hoang của người dì để đón Giáng Sinh “đổi gió”, nhưng lại không hề biết họ sắp đối đầu… chủ nhà thực sự: một đại gia đình chuột đã định cư từ lâu và cực kỳ ghét bị làm phiền. Cuộc chiến giành lãnh thổ bùng nổ — bẫy giăng khắp nơi, ai nhanh hơn, ai thông minh hơn sẽ sống yên thân!',
    posterUrl:
      'https://cinestar.com.vn/_next/image/?url=https%3A%2F%2Fapi-website.cinestar.com.vn%2Fmedia%2Fwysiwyg%2FPosters%2F12-2025%2Fmac-bay-lu-ti-quay.jpeg&w=1080&q=75',
    trailerUrl: 'https://youtu.be/kcjXkv2XeHI',
    ratingAge: 'P',
    country: 'Norway',
    language: 'Norwegian',
    actors: ['Vivild Falk Berg', 'Vegard Strand Eide', 'Charlotte Frogner'],
    director: 'Henrik Martin Dahlsbakken',
    producer: undefined,
    ...generateRandomDates(),
  },
  {
    title: 'KUMANTHONG NHẬT BẢN: VONG NHI CÚP BẾ (T16)',
    genres: ['Horror', 'Mystery'],
    duration: 110,
    description:
      'Một người mẹ — Suzuki Yoshie — sau khi mất con gái, bỗng tìm thấy một con búp bê giống hệt bé. Vì quá đau lòng, vợ chồng cô chăm sóc búp bê như con, nhiều năm sau khi cô mang thai, họ phát hiện con búp bê dường như không muốn chia sẻ tình thương với “đứa em” sắp chào đời — và những hiện tượng kỳ quái, ám ảnh bắt đầu xảy ra. Một câu chuyện kinh dị, ám ảnh về nỗi đau mất con, mê tín và cái giá của việc níu giữ quá khứ. ',
    posterUrl:
      'https://cinestar.com.vn/_next/image/?url=https%3A%2F%2Fapi-website.cinestar.com.vn%2Fmedia%2Fwysiwyg%2FPosters%2F12-2025%2Fkumanthong-nhat-ban-vong-nhi-cup-be.jpeg&w=1080&q=75',
    trailerUrl: 'https://youtu.be/xcYVKTYnRCc',
    ratingAge: 'C13',
    country: 'Japan',
    language: 'Japanese',
    actors: [
      'Kôji Seto',
      'Masami Nagasawa',
      'Tetsushi Tanaka',
      'Jun Fubuki',
      'Ken Yasuda',
    ],
    director: 'Yaguchi Shinobu',
    producer: undefined,
    ...generateRandomDates(),
  },
  {
    title: 'VUA CỦA CÁC VUA (PĐ)',
    genres: ['Animation'],
    duration: 99,
    description:
      'Khi một bộ phim hoạt hình Hàn Quốc kể lại câu chuyện từ kinh thánh — “Vua của Các Vua” đem đến một hành trình kỳ vĩ về đức tin, phép màu và hy vọng, thông qua nét vẽ đầy cảm xúc và hình ảnh thiêng liêng.',
    posterUrl:
      'https://cinestar.com.vn/_next/image/?url=https%3A%2F%2Fapi-website.cinestar.com.vn%2Fmedia%2Fwysiwyg%2FPosters%2F12-2025%2Fvua-cua-cac-vua.png&w=1080&q=75',
    trailerUrl: 'https://youtu.be/6g5TvVyc65g',
    ratingAge: 'P',
    country: 'South Korea',
    language: 'Korean',
    actors: ['Mark Hamill', 'Pierce Brosnan', 'Roman Griffin Davis'],
    director: 'Seong-ho Jang',
    producer: undefined,
    ...generateRandomDates(),
  },
  {
    title: 'PHIM ĐIỆN ẢNH ANH TRAI TÔI LÀ KHỦNG LONG: TƯƠNG LAI CỦA QUÁ KHỨ',
    genres: ['Animation'],
    duration: 95,
    description:
      'Tựa như một cuộc hành trình xuyên thời gian đầy ly kỳ — khi một ác quỷ tưởng đã bị diệt trừ bỗng trở lại hung dữ hơn, hai nhân vật Phong và Nghi buộc phải ngược dòng về thời khắc trước thảm họa để thay đổi số phận loài người. Nhưng đổi lại, họ phải đánh đổi chính sự tồn tại của mình. Một bộ phim hoạt hình thần thoại — hành động, đấu tranh giữa thiện và ác — mở ra thử thách khốc liệt cho nhân loại.',
    posterUrl:
      'https://cinestar.com.vn/_next/image/?url=https%3A%2F%2Fapi-website.cinestar.com.vn%2Fmedia%2Fwysiwyg%2FPosters%2F12-2025%2Fanh-trai-toi-la-khung-long.png&w=1080&q=75',
    trailerUrl: undefined,
    ratingAge: 'P',
    country: undefined,
    language: undefined,
    actors: [],
    director: undefined,
    producer: undefined,
    ...generateRandomDates(),
  },
  {
    title: 'EM SẼ KHỬ ANH (T18)',
    genres: ['Thriller', 'Comedy'],
    duration: 118,
    description:
      'Một cặp đôi trẻ — Grace và Jackson — rời New York để chuyển đến ngôi nhà thừa kế tại vùng quê yên tĩnh. Giữa không gian cô lập, Grace vật lộn với chứng trầm cảm sau sinh và cố gắng tìm lại chính mình trong vai trò người mẹ. Nhưng khi cô dần rơi vào trạng thái rạn vỡ và hỗn loạn, đó không phải vì yếu đuối, mà chính nhờ trí tưởng tượng, nghị lực và sức sống mãnh liệt hoang dã, cô tìm thấy lại con người thật của mình.',
    posterUrl:
      'https://cinestar.com.vn/_next/image/?url=https%3A%2F%2Fapi-website.cinestar.com.vn%2Fmedia%2Fwysiwyg%2FPosters%2F12-2025%2Fem-se-khu-anh.png&w=1080&q=75',
    trailerUrl: undefined,
    ratingAge: undefined,
    country: undefined,
    language: undefined,
    actors: ['Jennifer Lawrence', 'Robert Pattinson', 'Sissy Spacek'],
    director: 'Lynne Ramsay',
    producer: undefined,
    ...generateRandomDates(),
  },
  {
    title: 'CHỢ ĐEN THỜI TẬN THẾ',
    genres: ['Thriller'],
    duration: 99,
    description:
      'Trong thế giới hậu tận thế sau trận động đất thảm khốc, một tòa nhà chung cư không bị sụp đổ đã trở thành một khu chợ trao đổi hàng hóa — nơi quyền lực, sinh tồn và tham vọng giao tranh, thử thách nhân tính ở mức cao nhất.',
    posterUrl:
      'https://cinestar.com.vn/_next/image/?url=https%3A%2F%2Fapi-website.cinestar.com.vn%2Fmedia%2Fwysiwyg%2FPosters%2F12-2025%2Fcho-den-thoi-tan-the.jpg&w=1080&q=75',
    trailerUrl: 'https://youtu.be/ktjCLQ0raB8',
    ratingAge: undefined,
    country: undefined,
    language: undefined,
    actors: ['Lee Jae-in', 'Hong Kyung', 'Jeong Man-sik'],
    director: 'Hong Gi-Won',
    producer: undefined,
    ...generateRandomDates(),
  },
  {
    title: 'ĐỤNG ĐỘ SIÊU TRĂN',
    genres: ['Adventure'],
    duration: 99,
    description:
      'Doug và Griff — hai người bạn thân từ nhỏ — quyết định làm lại bộ phim kinh điển yêu thích của mình. Họ tiến sâu vào rừng Amazon để quay phim, nhưng mọi chuyện trở nên cực kỳ nguy hiểm khi một con trăn khổng lồ thực sự xuất hiện, biến chuyến phiêu lưu thành cuộc đấu sinh tử giữa con người và thiên nhiên hoang dã.',
    posterUrl:
      'https://cinestar.com.vn/_next/image/?url=https%3A%2F%2Fapi-website.cinestar.com.vn%2Fmedia%2Fwysiwyg%2FPosters%2F12-2025%2FAnaconda.jpg&w=1080&q=75',
    trailerUrl: 'https://youtu.be/vJiB77BGGxU',
    ratingAge: undefined,
    country: undefined,
    language: undefined,
    actors: ['Jack Black', 'Paul Rudd', 'Steve Zahn'],
    director: 'Tom Gormican',
    producer: undefined,
    ...generateRandomDates(),
  },
  {
    title: 'CÔ HẦU GÁI',
    genres: ['Thriller'],
    duration: 99,
    description:
      "Millie — một cô gái với quá khứ bí ẩn — trở thành bảo mẫu cho một gia đình giàu có. Khi bước chân vào biệt thự sang trọng và nhận công việc 'trong mơ', cô nhanh chóng nhận ra rằng phía sau vẻ ngoài xa hoa là một mạng lưới bí mật, cạm bẫy và nguy hiểm — nơi thanh sạch chỉ là mặt nạ.",
    posterUrl:
      'https://cinestar.com.vn/_next/image/?url=https%3A%2F%2Fapi-website.cinestar.com.vn%2Fmedia%2Fwysiwyg%2FPosters%2F12-2025%2Fco-hau-gai.jpg&w=1080&q=75',
    trailerUrl: undefined,
    ratingAge: undefined,
    country: undefined,
    language: undefined,
    actors: ['Sydney Sweeney', 'Brandon Sklenar', 'Amanda Seyfried'],
    director: 'Paul Feig',
    producer: undefined,
    ...generateRandomDates(),
  },
  {
    title: 'THIÊN ĐƯỜNG MÁU',
    genres: ['Romance', 'Action'],
    duration: 99,
    description:
      'Thiên Đường Máu là phim điện ảnh đầu tiên về nạn lừa đảo người Việt ra nước ngoài. Tin lời hứa “việc nhẹ lương cao”, không ít thanh niên bị đưa đến những “đặc khu”, nơi họ trải qua cảnh giam lỏng và bị ép buộc phải gọi điện để lừa ngược lại chính đồng bào mình. Nhiều người trong số đó đã tìm cách đào thoát khỏi địa ngục mà họ đã trót dấn thân vào.',
    posterUrl:
      'https://cinestar.com.vn/_next/image/?url=https%3A%2F%2Fapi-website.cinestar.com.vn%2Fmedia%2Fwysiwyg%2FPosters%2F12-2025%2Fthien-duong-mau-poster.png&w=1080&q=75',
    trailerUrl: 'https://youtu.be/QeLB2BuXaM0',
    ratingAge: undefined,
    country: 'Vietnam',
    language: 'Vietnamese',
    actors: ['Quang Tuấn', 'Hoài Lâm', 'Quách Ngọc Ngoan'],
    director: 'Hoàng Tuấn Cường',
    producer: undefined,
    ...generateRandomDates(),
  },
  {
    title: 'AI THƯƠNG AI MẾN',
    genres: ['Comedy', 'Family', 'Drama'],
    duration: 99,
    description:
      'Phim lấy bối cảnh miền Tây sông nước năm 1960, kể về hành trình cuộc đời của Mến – người phụ nữ trải qua nhiều biến cố, thăng trầm để tìm lại ý nghĩa của yêu thương và bình yên trong cuộc sống.',
    posterUrl:
      'https://cinestar.com.vn/_next/image/?url=https%3A%2F%2Fapi-website.cinestar.com.vn%2Fmedia%2Fwysiwyg%2FPosters%2F01-2026%2Fai-men-ai-thuong-poster.jpeg&w=1080&q=75',
    trailerUrl: 'https://youtu.be/Z5QDdTiDgto',
    ratingAge: undefined,
    country: 'Vietnam',
    language: 'Vietnamese',
    actors: [
      'Ngọc Thuận',
      'Thu Trang',
      'Trâm Anh',
      'Võ Điền Gia Huy',
      'Khả Như',
      'La Thành',
      'Trương Minh Thảo',
    ],
    director: 'Thu Trang',
    producer: undefined,
    ...generateRandomDates(),
  },
  {
    title: 'CON KỂ BA NGHE',
    genres: ['Family', 'Drama'],
    duration: 99,
    description:
      'Một nghệ sĩ xiếc đi trên dây và cậu con trai — trong hành trình tìm lại sự kết nối đã đánh mất — dần mở lòng, chữa lành những tổn thương cũ. Phim vừa tôn vinh nghề xiếc Việt Nam, vừa nhắc nhớ giá trị gia đình giữa nhịp sống hiện đại.',
    posterUrl:
      'https://cinestar.com.vn/_next/image/?url=https%3A%2F%2Fapi-website.cinestar.com.vn%2Fmedia%2Fwysiwyg%2FPosters%2F01-2026%2Fcon-ke-ba-nghe-poster.jpg&w=1080&q=75',
    trailerUrl: 'https://youtu.be/AosY6TeYB_U',
    ratingAge: undefined,
    country: 'Vietnam',
    language: 'Vietnamese',
    actors: [],
    director: 'Đỗ Quốc Trung',
    producer: undefined,
    ...generateRandomDates(),
  },
  {
    title: 'MÙI PHỞ',
    genres: ['Romance', 'Family'],
    duration: 99,
    description: undefined,
    posterUrl:
      'https://cinestar.com.vn/_next/image/?url=https%3A%2F%2Fapi-website.cinestar.com.vn%2Fmedia%2Fwysiwyg%2FPosters%2F02-2026%2Fmui-pho.jpg&w=1080&q=75',
    trailerUrl: undefined,
    ratingAge: undefined,
    country: 'Vietnam',
    language: 'Vietnamese',
    actors: [],
    director: undefined,
    producer: undefined,
    ...generateRandomDates(),
  },
  {
    title: 'BÁU VẬT TRỜI CHO',
    genres: ['Romance', 'Comedy', 'Family'],
    duration: 99,
    description:
      'Khi một cậu bé sáu tuổi trong một gia đình đơn thân vô tình tìm được “người cha trời cho” của mình — mọi bí mật và định mệnh trớ trêu bị lật mở. Bộ phim gia đình hoành tráng dịp Tết 2026, kể về hành trình tìm lại gốc rễ, tình thân và khám phá giá trị thực sự của cuộc sống.',
    posterUrl:
      'https://cinestar.com.vn/_next/image/?url=https%3A%2F%2Fapi-website.cinestar.com.vn%2Fmedia%2Fwysiwyg%2FPosters%2F02-2026%2Fbau-vat-troi-cho.jpg&w=1080&q=75',
    trailerUrl: 'https://youtu.be/yiXKz5qFivc',
    ratingAge: undefined,
    country: 'Vietnam',
    language: 'Vietnamese',
    actors: [
      'NSND Kim Xuân',
      'Tuấn Trần',
      'Phương Anh Đào',
      'Võ Tấn Phát',
      'Hưng Nguyễn',
      'La Thành',
      'Trung Dân',
      'Khương Lê',
      'Tạ Lâm',
      'Quách Ngọc Ngoan',
    ],
    director: 'Lê Thanh Sơn',
    producer: undefined,
    ...generateRandomDates(),
  },
  {
    title: 'PHIM SUPER MARIO THIÊN HÀ',
    genres: ['Animation'],
    duration: 99,
    description:
      'Một phần mới trong vũ trụ Super Mario — PHIM SUPER MARIO THIÊN HÀ đưa khán giả vào hành trình trong không gian rộng lớn, nơi Mario và bạn bè đối mặt với thử thách để bảo vệ vũ trụ khỏi thế lực đen tối.',
    posterUrl:
      'https://cinestar.com.vn/_next/image/?url=https%3A%2F%2Fapi-website.cinestar.com.vn%2Fmedia%2Fwysiwyg%2FPosters%2F04-2026%2Fmario.jpg&w=1080&q=75',
    trailerUrl: 'https://youtu.be/pY0u714WV3M',
    ratingAge: 'P',
    country: undefined,
    language: undefined,
    actors: [
      'Chris Pratt',
      'Anya Taylor-Joy',
      'Charlie Day',
      'Jack Black',
      'Keegan-Michael Key',
      'Benny Safdie',
      'Kevin Michael Richardson',
      'Brie Larson',
    ],
    director: 'Aaron Horvath, Michael Jelenic',
    producer: undefined,
    ...generateRandomDates(),
  },
  {
    title: 'ĐẠI TIỆC TRĂNG MÁU 8',
    genres: ['Drama', 'Comedy', 'Horror'],
    duration: 99,
    description:
      '“Đại tiệc trăng máu 8” không chỉ là một bộ phim — đó là sự phơi bày tàn khốc những áp lực sau ống kính. Khi ở ranh giới giữa diễn xuất và bạo lực phim trường, liệu ai mới thực sự là nạn nhân trong cuộc chiến sinh tồn này?',
    posterUrl:
      'https://cinestar.com.vn/_next/image/?url=https%3A%2F%2Fapi-website.cinestar.com.vn%2Fmedia%2Fwysiwyg%2FPosters%2F12-2025%2Fdai-tiec-trang-mau.jpg&w=1080&q=75',
    trailerUrl: undefined,
    ratingAge: 'C13',
    country: 'Vietnam',
    language: 'Vietnamese',
    actors: [
      'Miu Lê',
      'Liên Bỉnh Phát',
      'Hứa Vĩ Văn',
      'Hồng Ánh',
      'Đức Khuê',
      'Quỳnh Lý',
      'Quốc Khánh',
    ],
    director: 'Phan Gia Nhật Linh',
    producer: undefined,
    ...generateRandomDates(),
  },
  {
    title: 'MORTAL KOMBAT: CUỘC CHIẾN SINH TỬ II',
    genres: ['Action', 'Adventure', 'Fantasy'],
    duration: 99,
    description:
      'Phần tiếp theo bom tấn chuyển thể từ trò chơi đình đám — khi các nhà vô địch phải đối mặt trong một trận chiến đẫm máu để bảo vệ Earthrealm khỏi thế lực đen tối Shao Kahn. Một cuộc chiến khốc liệt nơi sinh tồn và danh dự quyết định vận mệnh vũ trụ.',
    posterUrl:
      'https://cinestar.com.vn/_next/image/?url=https%3A%2F%2Fapi-website.cinestar.com.vn%2Fmedia%2Fwysiwyg%2FPosters%2F05-2025%2FMORTAL_KOMBAT_II-Teaser_Poster-700x1000_1_.jpg&w=1080&q=75',
    trailerUrl: 'https://youtu.be/OxFuEBUHJFU',
    ratingAge: undefined,
    country: undefined,
    language: undefined,
    actors: [
      'Karl Urban',
      'Adeline Rudolph',
      'Jessica McNamee',
      'Josh Lawson',
      'Ludi Lin',
      'Mehcad Brooks',
      'Tati Gabrielle',
      'Lewis Tan',
    ],
    director: 'Simon McQuoid',
    producer: undefined,
    ...generateRandomDates(),
  },
  {
    title: 'NHÀ HAI CHỦ',
    genres: ['Horror'],
    duration: 99,
    description:
      'Một gia đình nhỏ vì không đủ điều kiện đã phải mua một căn nhà mà người dân xung quanh đồn đoán rằng có nhiều điều tâm linh kỳ lạ. Liệu họ sẽ đối mặt với ngôi nhà nhiều chủ sẽ như thế nào?',
    posterUrl:
      'https://cinestar.com.vn/_next/image/?url=https%3A%2F%2Fapi-website.cinestar.com.vn%2Fmedia%2Fwysiwyg%2FPosters%2F12-2025%2Fnha-hai-chu-payoff.jpg&w=1080&q=75',
    trailerUrl: 'https://youtu.be/oRxJOh8FrUA',
    ratingAge: 'C13',
    country: 'Việt Nam',
    language: 'Vietnamese',
    actors: ['Trâm Anh', 'Kim Hải', 'Tạ Lâm', 'Kim Phương', 'Mộc Trà'],
    director: 'Trần Duy Linh, Phạm Trung Hiếu',
    producer: undefined,
    ...generateRandomDates(),
  },
  {
    title: 'CHÀNG MÈO MANG MŨ',
    genres: ['Animation', 'Family', 'Adventure'],
    duration: 99,
    description:
      'Trong phim, Chàng Mèo Mang Mũ nhận nhiệm vụ khó khăn nhất từ trước đến nay từ tổ chức I.I.I.I. (Viện Sáng Tạo và Cảm Hứng): cổ vũ tinh thần cho Gabby và Sebastian — hai anh em đang vật lộn với việc thích nghi sau khi chuyển đến một thị trấn mới. Với “thành tích” thường xuyên làm quá mọi chuyện, lần này có thể sẽ là cơ hội cuối cùng để anh chàng chuyên gây rối chứng minh bản thân nếu không muốn mất đi chiếc mũ thần kỳ!',
    posterUrl:
      'https://cinestar.com.vn/_next/image/?url=https%3A%2F%2Fapi-website.cinestar.com.vn%2Fmedia%2Fwysiwyg%2FPosters%2F11-2025%2FTHE_CAT_IN_THE_HAT-Teaser_Poster-061126-700x1000.jpg&w=1080&q=75',
    trailerUrl: undefined,
    ratingAge: 'P',
    country: undefined,
    language: undefined,
    actors: [
      'Bill Hader',
      'Xochitl Gomez',
      'Matt Berry',
      'Quinta Brunson',
      'Paula Pell',
    ],
    director: 'Alessandro Carloni, Erica Rivinoja',
    producer: undefined,
    ...generateRandomDates(),
  },
  {
    title: 'SPONGEBOB: LỜI NGUYỀN HẢI TẶC',
    genres: ['Animation', 'Comedy', 'Adventure'],
    duration: 99,
    description:
      'SpongeBob phiêu lưu xuống đáy đại dương để đối mặt với hồn ma của Người Hà Lan bay, vượt qua thử thách và khám phá những bí ẩn dưới biển.',
    posterUrl:
      'https://cinestar.com.vn/_next/image/?url=https%3A%2F%2Fapi-website.cinestar.com.vn%2Fmedia%2Fwysiwyg%2FPosters%2F12-2025%2Fspongebob-poster.png&w=1080&q=75',
    trailerUrl: 'https://youtu.be/lRgJyuBu8IA',
    ratingAge: 'P',
    country: undefined,
    language: undefined,
    actors: [
      'Tom Kenny',
      'Clancy Brown',
      'Rodger Bumpass',
      'Bill Fagerbakke',
      'Carolyn Lawrence',
      'Mr. Lawrence',
      'George Lopez',
      'Isis “Ice Spice” Gaston',
      'Arturo Castro',
      'Sherry Cola',
      'Regina Hall',
      'Mark Hamill',
    ],
    director: 'Derek Drymon',
    producer: undefined,
    ...generateRandomDates(),
  },
  {
    title: 'THOÁT KHỎI TẬN THẾ',
    genres: ['Adventure', 'Sci-Fi'],
    duration: 99,
    description:
      'Ryland Grace tỉnh dậy trong một con tàu vũ trụ mà không hề nhớ gì — anh phát hiện mình là người duy nhất còn sống sót của sứ mệnh Hail Mary, được gửi tới hệ sao Tau Ceti để tìm cách cứu Trái Đất khỏi thảm họa. Trên con tàu, anh gặp một sinh vật ngoài hành tinh mà anh đặt tên là Rocky; cùng nhau, họ phải đấu tranh để sống sót và tìm hi vọng cho nhân loại.',
    posterUrl:
      'https://cinestar.com.vn/_next/image/?url=https%3A%2F%2Fapi-website.cinestar.com.vn%2Fmedia%2Fwysiwyg%2FPosters%2F03-2026%2Fthoat-khoi-tan-the.jpg&w=1080&q=75',
    trailerUrl: undefined,
    ratingAge: undefined,
    country: undefined,
    language: undefined,
    actors: [
      'Ryan Gosling',
      'Liz Kingsman',
      'Milana Vayntrub',
      'Sandra Hüller',
    ],
    director: 'Phil Lord, Christopher Miller',
    producer: undefined,
    ...generateRandomDates(),
  },
  {
    title: 'CÚ NHẢY KỲ DIỆU',
    genres: ['Animation', 'Comedy', 'Family', 'Adventure'],
    duration: 99,
    description:
      'Hoppers (Cú Nhảy Kỳ Diệu) — một bộ phim hoạt hình hài hước, vui nhộn và đầy tính phiêu lưu. Nếu bạn từng thích nét hài hước của loạt phim “We Bare Bears”, thì Hoppers sẽ mang đến một “rừng thú” đáng yêu, với lối kể chuyện nhẹ nhàng, dễ thương và phù hợp cho gia đình, trẻ em. Phim do đạo diễn Daniel Chong thực hiện, hướng đến đối tượng khán giả ở mọi lứa tuổi. ',
    posterUrl:
      'https://cinestar.com.vn/_next/image/?url=https%3A%2F%2Fapi-website.cinestar.com.vn%2Fmedia%2Fwysiwyg%2FPosters%2F03-2026%2Fhoopers-poster.jpg&w=1080&q=75',
    trailerUrl: undefined,
    ratingAge: 'P',
    country: undefined,
    language: undefined,
    actors: ['Jon Hamm', 'Bobby Moynihan', 'Piper Curda'],
    director: 'Daniel Chong',
    producer: undefined,
    ...generateRandomDates(),
  },
];
