// src/api/mockData.ts
import { type Movie } from "../types";

export const MOCK_MOVIES: Movie[] = [
  {
    movie_id: "1",
    title: "MY LITTLE GRANDMA (T13)",
    director: "Nguyễn Hoàng Phúc",
    poster_url:
      "https://www.cgv.vn/media/catalog/product/cache/1/image/1800x/71252117777b696995f01934522c402d/4/7/470wx700h-cvcn_1.jpg",
    rating_age: 13,
    description: `Inspired by the sweet memories of childhood, “My Little Grandma” tells a heartfelt story about the bond between a grandmother and her grandchild in a small, close-knit neighborhood. Mrs. Hau – a woman who has spent her whole life working hard – suddenly becomes the only support for her young grandchild after her daughter leaves. Though life is full of struggles, her love never fades. To her, the child is her “little treasure” – her joy, her comfort, and the very reason she keeps going. The film gently invites the audience into everyday moments of this small community: the child’s innocent laughter, the grandmother’s protective embrace, and the kindness of caring neighbors. Together, they weave a warm portrait of family, childhood, and the simple yet enduring beauty of human connection.`,
    genre: "Family, Drama",
    duration: 120,
    language: "Vietnamese",
    country: "Vietnam",
    release_date: "2025-10-16",
    end_date: "2025-11-16",
    trailer_url: "https://www.youtube.com/watch?v=_cj77qa_wMc",
  },
  {
    movie_id: "2",
    title: "PREDATOR: BADLANDS (T18)",
    director: "Ethan Rodriguez",
    poster_url:
      "https://www.cgv.vn/media/catalog/product/cache/3/image/c5f0a1eff4c394a251036189ccddaacd/c/g/cgv_pd_up.jpg",
    rating_age: 18,
    description: `Trong tương lai, tại một hành tinh hẻo lánh, một Predator non nớt - kẻ bị chính tộc của mình ruồng bỏ - tìm thấy một đồng minh không ngờ tới là Thia và bắt đầu hành trình sinh tử nhằm truy tìm kẻ thù tối thượng. Bộ phim do Dan Trachtenberg - đạo diễn của Prey chỉ đạo và nằm trong chuỗi thương hiệu Quái Thú Vô Hình Predator.`,
    genre: "Adventure, Action",
    duration: 110,
    language: "English",
    country: "America",
    release_date: "2025-11-07",
    end_date: "2025-12-07",
    trailer_url: "https://www.youtube.com/watch?v=43R9l7EkJwE",
  },
  {
    movie_id: "3",
    title: "GODZILLA MINUS ONE (T13)",
    director: "Takashi Yamazaki",
    poster_url: "https://cinema.momocdn.net/img/57240060814553111-minus.png?size=M",
    rating_age: 13,
    description: `Năm 1945, khi Thế chiến thứ Hai đang đi đến hồi kết, phi công Nhật Bản Koichi Shikishima bất ngờ chạm trán một quái vật biển đến từ cõi ngoài, mà người dân trên đảo Odo gọi là Godzilla. Bị giày vò bởi nỗi tội lỗi của kẻ sống sót — vì không thể bắn hạ con quái vật bằng súng gắn trên máy bay, và vì đã bỏ lại nhiệm vụ cảm tử của mình — Shikishima tìm được chút niềm an ủi mong manh bên Noriko, một người phụ nữ sống sót sau các đợt không kích Tokyo, và Akiko, một bé gái mồ côi. Năm tháng trôi qua, Shikishima dần mở lòng với Noriko và những người xung quanh. Nhưng bóng ma quá khứ — lần chạm trán năm xưa với Godzilla, nay đã biến đổi và nhiễm phóng xạ — lại một lần nữa trỗi dậy, khi toàn bộ nước Nhật chìm trong tuyệt vọng và kinh hoàng.`,
    genre: "Action",
    duration: 135,
    language: "Japanese",
    country: "Japan",
    release_date: "2025-11-09",
    end_date: "2025-12-09",
    trailer_url: "https://www.youtube.com/watch?v=nAYKaslCXPc",
  },
  {
    movie_id: "4",
    title: "TRÁI TIM QUÈ QUẶT (T16)",
    director: "Trần Công Minh",
    poster_url:
      "https://www.cgv.vn/media/catalog/product/cache/1/image/c5f0a1eff4c394a251036189ccddaacd/3/5/350x495_2_1.jpg",
    rating_age: 16,
    description: `Một vụ án mạng tàn bạo làm chấn động thị trấn yên bình. Khi thi thể người phụ nữ bị sát hại dã man được phát hiện, mọi nghi ngờ đổ dồn vào Sơn — có thể là người tình của nạn nhân. Triết, một nhà điêu khắc danh tiếng, rơi vào giằng xé giữa nghi ngờ và tình thân khi anh cùng vợ mình cố gắng tìm cách minh oan cho em trai. Rốt cuộc, Sơn là kẻ giết người, nạn nhân của định mệnh nghiệt ngã, hay một trái tim lạc lối bị cuốn vào tình yêu đến mức tự hủy diệt.`,
    genre: "Nervous, Drama",
    duration: 100,
    language: "Vietnamese",
    country: "Vietnam",
    release_date: "2025-11-05",
    end_date: "2025-12-05",
    trailer_url: "https://www.youtube.com/watch?v=6I6Zk9WxLtE",
  },
  {
    movie_id: "5",
    title: "NHÀ MA XÓ (T16)",
    director: "Phạm Thanh Bình",
    poster_url:
      "https://www.cgv.vn/media/catalog/product/cache/1/image/c5f0a1eff4c394a251036189ccddaacd/3/5/350x495-nhamaxo.jpg",
    rating_age: 16,
    description: `Nhà Ma Xó xoay quanh câu chuyện về bà Hiền, người phụ nữ một mình nuôi 3 người con sau tai nạn chồng qua đời. Mọi chuyện bắt đầu khi người con trai giữa trong một lần thả lưới bắt cá vớt được một cái khạp bằng sành, nắp đậy kín. Từ đó, những hiện tượng kỳ quái liên tiếp xảy ra trong gia đình.`,
    genre: "Family, Horror",
    duration: 100,
    language: "Vietnamese",
    country: "Vietnam",
    release_date: "2025-10-24",
    end_date: "2025-11-24",
    trailer_url: "https://www.youtube.com/watch?v=DUMiVY9jOls",
  },
  {
    movie_id: "6",
    title: "NAK RAK MAK, MAAK MAK (T13)",
    director: "Wanchai Darawan",
    poster_url: "https://cdn.galaxycine.vn/media/2025/10/27/tinh-nguoi-duyen-ma-500_1761537469837.jpg",
    rating_age: 13,
    description: `Lấy cảm hứng từ truyền thuyết dân gian Thái Lan về hồn ma Mae Nak, Tình Người Duyên Ma: Nhắm Mak Yêu Luôn kể câu chuyện tình vượt thời gian giữa nàng Nak và chàng Mak. Xuyên không đến 200 năm sau, Nak bất ngờ được vào vai nữ chính trong chính bộ phim về truyền thuyết của mình. Tình cờ thay, vai nam chính lại được thủ bởi Mak - lúc này đã là một nam diễn viên nổi tiếng toàn quốc. Ở đây, Nak phải chinh phục lại trái tim Mak trong vòng 30 ngày mà không được dùng đến ma lực, để có thể ở bên anh trọn đời trọn kiếp.`,
    genre: "Romance, Comedy, Horror",
    duration: 104,
    language: "Thai",
    country: "Thailand",
    release_date: "2025-11-07",
    end_date: "2025-12-07",
    trailer_url: "https://www.youtube.com/watch?v=KDvKu6rf31s",
  },
  {
    movie_id: "7",
    title: "THAI CHIÊU TÀI (T16)",
    director: "Lê Phước Thành",
    poster_url:
      "https://www.cgv.vn/media/catalog/product/cache/1/image/1800x/71252117777b696995f01934522c402d/4/5/457x590-tct_1.jpg",
    rating_age: 16,
    description: `Nhơn, một doanh nhân thành đạt nhờ thủ đoạn và mưu mẹo, tìm đến thứ tà thuật mang tên “Thai Chiêu Tài” để giữ lấy tài khí đã vô tình khơi dậy những ám ảnh từ quá khứ và sang chấn liên thế hệ.`,
    genre: "Horror",
    duration: 104,
    language: "Vietnamese",
    country: "Vietnam",
    release_date: "2025-11-20",
    end_date: "2025-12-20",
    trailer_url: "https://www.youtube.com/watch?v=3ChaZC1zjwU",
  },
  {
    movie_id: "8",
    title: "HAUNTED MOUNTAINS: THE YELLOW TABOO (T16)",
    director: "Lin Wei-Sheng",
    poster_url:
      "https://www.cgv.vn/media/catalog/product/cache/3/image/c5f0a1eff4c394a251036189ccddaacd/3/5/350x495-nui-te-vong.jpg",
    rating_age: 16,
    description: `A legend in Taiwan's mountains says that when lost, hikers encounter a figure in a yellow raincoat who points to a blurry path, leading them to disappear.`,
    genre: "Horror",
    duration: 100,
    language: "Chinese",
    country: "Taiwan",
    release_date: "2025-11-25",
    end_date: "2025-12-25",
    trailer_url: "https://www.youtube.com/watch?v=th24BWV__n8",
  },
  {
    movie_id: "9",
    title: "THE WOMAN IN THE WHITE CAR (T16)",
    director: "Park Ji-Hoon",
    poster_url:
      "https://www.cgv.vn/media/catalog/product/cache/3/image/c5f0a1eff4c394a251036189ccddaacd/t/w/twitwc.jpg",
    rating_age: 16,
    description: `Everyone lies… In the early hours after a raging snowstorm, Do Kyung (Jung Ryeo-won) rushes her blood-soaked sister to the hospital, begging for help. But when detective Hyun Joo (Lee Jung-eun) arrives at the scene, she senses that something in Do Kyung’s frantic testimony doesn’t add up. As each person recalls the incident from a different perspective, truth and deception begin to intertwine—unraveling a haunting psychological mystery where no one’s memory can be trusted. On that snowy night when every trace was buried, who is the real culprit?`,
    genre: "Nervous, Drama",
    duration: 108,
    language: "Korean",
    country: "Korea",
    release_date: "2025-11-18",
    end_date: "2025-12-18",
    trailer_url: "https://www.youtube.com/watch?v=th24BWV__n8",
  },

  {
    movie_id: "10",
    title: "ZOOTOPIA 2 (T13)",
    director: "Nguyễn Hoàng Phúc",
    poster_url:
      "https://www.cgv.vn/media/catalog/product/cache/1/image/c5f0a1eff4c394a251036189ccddaacd/t/e/teaser2_poster_vietnam.jpg",
    rating_age: 13,
    description: `Brave rabbit cop Judy Hopps and her friend, the fox Nick Wilde, 
      team up again to crack a new case, the most perilous and intricate of their careers.`,
    genre: "Family, Fantasy",
    duration: 99,
    language: "Vietnamese",
    country: "America",
    release_date: "2025-11-23",
    end_date: "2025-12-23",
    trailer_url: "https://www.youtube.com/watch?v=5O3LEps6WJY",
  },
  {
    movie_id: "11",
    title: "QUÁN KỲ NAM (T13)",
    director: "Nguyễn Hoàng Phúc",
    poster_url:
      "https://images2.thanhnien.vn/thumb_w/686/528068263637045248/2025/7/28/anh-192-1753720738249804970853-0-0-1840-1382-crop-17537207981451620519791.jpg",
    rating_age: 13,
    description: `With the support of the authorities, Khang was assigned the job of translating “The Little Prince” 
      and moved into an empty apartment in an old apartment building. He became acquainted with a neighbor named Ky Nam, 
      who was once famous in the housework community and now quietly cooks monthly meals. 
      An accident occurred that prevented Ky Nam from continuing her work. 
      Khang offered to help and their relationship gradually deepened and became close. 
      Can their caring relationship last long amid the upheavals of today’s society?`,
    genre: "Drama, Romance",
    duration: 110,
    language: "Vietnamese",
    country: "Vietnam",
    release_date: "2025-11-27",
    end_date: "2025-12-27",
    trailer_url: "https://www.youtube.com/watch?v=27dgpqiI0VU",
  },
  {
    movie_id: "12",
    title: "MY FRIEND IS MURDERER (T16)",
    director: "Nguyễn Hoàng Phúc",
    poster_url:
      "https://www.bhdstar.vn/wp-content/uploads/2025/10/referenceSchemeHeadOfficeallowPlaceHoldertrueheight700ldapp-23.jpg",
    rating_age: 16,
    description: `The story of a murderer hiding in a peaceful rural village, 
      with only 30 days left before the statute of limitations expires.`,
    genre: "Comedy",
    duration: 123,
    language: "Korean",
    country: "Korea",
    release_date: "2025-11-28",
    end_date: "2025-12-28",
    trailer_url: "https://www.youtube.com/watch?v=6P5Nt6RdeZY",
  },
];
